"""create initial schema

Revision ID: 2bca21859cef
Revises:
Create Date: 2026-07-26 16:41:33.762319
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2bca21859cef"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "achievements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("icon", sa.String(length=50), nullable=False),
        sa.Column("xp_reward", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_achievements")),
        sa.UniqueConstraint("code", name=op.f("uq_achievements_code")),
    )
    op.create_table(
        "courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source_language", sa.String(length=50), nullable=False),
        sa.Column("target_language", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courses")),
    )
    with op.batch_alter_table("courses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_courses_code"), ["code"], unique=True)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("avatar_key", sa.String(length=50), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("hearts", sa.Integer(), nullable=False),
        sa.Column("max_hearts", sa.Integer(), nullable=False),
        sa.Column("gems", sa.Integer(), nullable=False),
        sa.Column("total_xp", sa.Integer(), nullable=False),
        sa.Column("current_streak", sa.Integer(), nullable=False),
        sa.Column("longest_streak", sa.Integer(), nullable=False),
        sa.Column("last_activity_date", sa.Date(), nullable=True),
        sa.Column("daily_goal_xp", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "current_streak >= 0", name=op.f("ck_users_non_negative_current_streak")
        ),
        sa.CheckConstraint("daily_goal_xp > 0", name=op.f("ck_users_positive_daily_goal")),
        sa.CheckConstraint("gems >= 0", name=op.f("ck_users_non_negative_gems")),
        sa.CheckConstraint("hearts <= max_hearts", name=op.f("ck_users_hearts_within_max")),
        sa.CheckConstraint("hearts >= 0", name=op.f("ck_users_non_negative_hearts")),
        sa.CheckConstraint(
            "longest_streak >= 0", name=op.f("ck_users_non_negative_longest_streak")
        ),
        sa.CheckConstraint("max_hearts > 0", name=op.f("ck_users_positive_max_hearts")),
        sa.CheckConstraint("total_xp >= 0", name=op.f("ck_users_non_negative_total_xp")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "daily_activity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("activity_date", sa.Date(), nullable=False),
        sa.Column("xp_earned", sa.Integer(), nullable=False),
        sa.Column("lessons_completed", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "lessons_completed >= 0", name=op.f("ck_daily_activity_non_negative_lessons")
        ),
        sa.CheckConstraint("xp_earned >= 0", name=op.f("ck_daily_activity_non_negative_xp")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_daily_activity_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_activity")),
        sa.UniqueConstraint("user_id", "activity_date", name=op.f("uq_daily_activity_user_id")),
    )
    with op.batch_alter_table("daily_activity", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_daily_activity_user_id"), ["user_id"], unique=False)

    op.create_table(
        "units",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("position > 0", name=op.f("ck_units_positive_position")),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_units_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_units")),
        sa.UniqueConstraint("course_id", "position", name=op.f("uq_units_course_id")),
    )
    with op.batch_alter_table("units", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_units_course_id"), ["course_id"], unique=False)

    op.create_table(
        "user_achievements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("achievement_id", sa.Integer(), nullable=False),
        sa.Column("unlocked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["achievement_id"],
            ["achievements.id"],
            name=op.f("fk_user_achievements_achievement_id_achievements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_achievements_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_achievements")),
        sa.UniqueConstraint("user_id", "achievement_id", name=op.f("uq_user_achievements_user_id")),
    )
    with op.batch_alter_table("user_achievements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_achievements_achievement_id"), ["achievement_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_user_achievements_user_id"), ["user_id"], unique=False)

    op.create_table(
        "skills",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=50), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("position > 0", name=op.f("ck_skills_positive_position")),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["units.id"], name=op.f("fk_skills_unit_id_units"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skills")),
        sa.UniqueConstraint("unit_id", "position", name=op.f("uq_skills_unit_id")),
    )
    with op.batch_alter_table("skills", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_skills_unit_id"), ["unit_id"], unique=False)

    op.create_table(
        "lessons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("xp_reward", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("position > 0", name=op.f("ck_lessons_positive_position")),
        sa.CheckConstraint("xp_reward > 0", name=op.f("ck_lessons_positive_xp_reward")),
        sa.ForeignKeyConstraint(
            ["skill_id"], ["skills.id"], name=op.f("fk_lessons_skill_id_skills"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lessons")),
        sa.UniqueConstraint("skill_id", "position", name=op.f("uq_lessons_skill_id")),
    )
    with op.batch_alter_table("lessons", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_lessons_skill_id"), ["skill_id"], unique=False)

    op.create_table(
        "skill_prerequisites",
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.Column("prerequisite_skill_id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "skill_id != prerequisite_skill_id",
            name=op.f("ck_skill_prerequisites_different_skills"),
        ),
        sa.ForeignKeyConstraint(
            ["prerequisite_skill_id"],
            ["skills.id"],
            name=op.f("fk_skill_prerequisites_prerequisite_skill_id_skills"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
            name=op.f("fk_skill_prerequisites_skill_id_skills"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "skill_id", "prerequisite_skill_id", name=op.f("pk_skill_prerequisites")
        ),
    )
    op.create_table(
        "user_skill_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.Column("lessons_completed", sa.Integer(), nullable=False),
        sa.Column("crowns", sa.Integer(), nullable=False),
        sa.Column("is_unlocked", sa.Boolean(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("crowns >= 0", name=op.f("ck_user_skill_progress_non_negative_crowns")),
        sa.CheckConstraint(
            "lessons_completed >= 0", name=op.f("ck_user_skill_progress_non_negative_lessons")
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
            name=op.f("fk_user_skill_progress_skill_id_skills"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_skill_progress_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_skill_progress")),
        sa.UniqueConstraint("user_id", "skill_id", name=op.f("uq_user_skill_progress_user_id")),
    )
    with op.batch_alter_table("user_skill_progress", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_skill_progress_skill_id"), ["skill_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_skill_progress_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "exercises",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column(
            "exercise_type",
            sa.Enum(
                "multiple_choice",
                "word_bank",
                "match_pairs",
                "fill_blank",
                "type_answer",
                name="exercise_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("instruction", sa.String(length=160), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("correct_answer", sa.Text(), nullable=True),
        sa.Column("answer_data", sa.JSON(), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("position > 0", name=op.f("ck_exercises_positive_position")),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.id"],
            name=op.f("fk_exercises_lesson_id_lessons"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercises")),
        sa.UniqueConstraint("lesson_id", "position", name=op.f("uq_exercises_lesson_id")),
    )
    with op.batch_alter_table("exercises", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_exercises_lesson_id"), ["lesson_id"], unique=False)

    op.create_table(
        "lesson_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "in_progress",
                "completed",
                "failed",
                "abandoned",
                name="attempt_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("hearts_at_start", sa.Integer(), nullable=False),
        sa.Column("hearts_remaining", sa.Integer(), nullable=False),
        sa.Column("correct_count", sa.Integer(), nullable=False),
        sa.Column("wrong_count", sa.Integer(), nullable=False),
        sa.Column("xp_earned", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "correct_count >= 0", name=op.f("ck_lesson_attempts_non_negative_correct_count")
        ),
        sa.CheckConstraint(
            "hearts_at_start >= 0", name=op.f("ck_lesson_attempts_non_negative_starting_hearts")
        ),
        sa.CheckConstraint(
            "hearts_remaining >= 0", name=op.f("ck_lesson_attempts_non_negative_remaining_hearts")
        ),
        sa.CheckConstraint(
            "wrong_count >= 0", name=op.f("ck_lesson_attempts_non_negative_wrong_count")
        ),
        sa.CheckConstraint("xp_earned >= 0", name=op.f("ck_lesson_attempts_non_negative_xp")),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.id"],
            name=op.f("fk_lesson_attempts_lesson_id_lessons"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_lesson_attempts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lesson_attempts")),
    )
    with op.batch_alter_table("lesson_attempts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lesson_attempts_lesson_id"), ["lesson_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_lesson_attempts_user_id"), ["user_id"], unique=False)

    op.create_table(
        "attempt_answers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attempt_id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("submitted_answer", sa.JSON(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["lesson_attempts.id"],
            name=op.f("fk_attempt_answers_attempt_id_lesson_attempts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
            name=op.f("fk_attempt_answers_exercise_id_exercises"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attempt_answers")),
        sa.UniqueConstraint(
            "attempt_id", "exercise_id", name=op.f("uq_attempt_answers_attempt_id")
        ),
    )
    with op.batch_alter_table("attempt_answers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_attempt_answers_attempt_id"), ["attempt_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_attempt_answers_exercise_id"), ["exercise_id"], unique=False
        )

    op.create_table(
        "exercise_options",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=255), nullable=False),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("pair_key", sa.String(length=64), nullable=True),
        sa.Column(
            "match_side",
            sa.Enum("left", "right", name="match_side", native_enum=False),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("position > 0", name=op.f("ck_exercise_options_positive_position")),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
            name=op.f("fk_exercise_options_exercise_id_exercises"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercise_options")),
        sa.UniqueConstraint(
            "exercise_id", "position", name=op.f("uq_exercise_options_exercise_id")
        ),
    )
    with op.batch_alter_table("exercise_options", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exercise_options_exercise_id"), ["exercise_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("exercise_options", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exercise_options_exercise_id"))

    op.drop_table("exercise_options")
    with op.batch_alter_table("attempt_answers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attempt_answers_exercise_id"))
        batch_op.drop_index(batch_op.f("ix_attempt_answers_attempt_id"))

    op.drop_table("attempt_answers")
    with op.batch_alter_table("lesson_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lesson_attempts_user_id"))
        batch_op.drop_index(batch_op.f("ix_lesson_attempts_lesson_id"))

    op.drop_table("lesson_attempts")
    with op.batch_alter_table("exercises", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exercises_lesson_id"))

    op.drop_table("exercises")
    with op.batch_alter_table("user_skill_progress", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_skill_progress_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_skill_progress_skill_id"))

    op.drop_table("user_skill_progress")
    op.drop_table("skill_prerequisites")
    with op.batch_alter_table("lessons", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lessons_skill_id"))

    op.drop_table("lessons")
    with op.batch_alter_table("skills", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skills_unit_id"))

    op.drop_table("skills")
    with op.batch_alter_table("user_achievements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_achievements_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_achievements_achievement_id"))

    op.drop_table("user_achievements")
    with op.batch_alter_table("units", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_units_course_id"))

    op.drop_table("units")
    with op.batch_alter_table("daily_activity", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_daily_activity_user_id"))

    op.drop_table("daily_activity")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))

    op.drop_table("users")
    with op.batch_alter_table("courses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_courses_code"))

    op.drop_table("courses")
    op.drop_table("achievements")
    # ### end Alembic commands ###
